### ISSUE TITLE
Instructions how to compile

### ISSUE THREAD

**Issue by sugarp0pe** [OmerYa/Invisi-Shell#1]
Greetings, sir,
Excuse my silly question, but сould  you provide more detailed instructions how to compile it properly?
Also thanks for awesome tool and great presentation at Derby!

**Comment by OmerYa** [comment]
The solution was built with Visual Studio 2013 so it should work with newer versions too. The second requirement is Windows Platform SDK (for the CLR Profiler API):
https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk

Let me know if it works for you.
