### ISSUE TITLE
Mitigation

### ISSUE THREAD

**Issue by scaery** [OmerYa/Invisi-Shell#2]
Nice talk, is there any way to mitigate this through GPO or is the problem still on the Powershell developers?

**Comment by OmerYa** [comment]
Microsoft did not update me on mitigation for Invisi-Shell. They do block now Invisi-Shell with Windows Defender using a very weak mechanism (a simple modification of source code bypasses this protection).

I'm not aware of any GPO that can prevent this method of attack.
